*set var ElasticSectionTag=SectionID
*if(ndime==3)
*if(strcmp(MatProp(Cross_section),"Rectangular")==0)
*set var height=MatProp(Height_h,real)
*set var width=MatProp(Width_b,real)
*set var A=operation(width*height)
*set var Iz=operation(width*width*width*height/12)
*set var Iy=operation(height*height*height*width/12)
*set var alpha=operation(max(height,width))
*set var beta=operation(min(height,width))
*set var J=operation(1-beta*beta*beta*beta/(12*alpha*alpha*alpha*alpha))
*set var J=operation(1.0/3-0.21*beta/alpha*J)
*set var J=operation(alpha*beta*beta*beta*J)
*elseif(strcmp(MatProp(Cross_section),"Tee")==0)
*set var height=MatProp(Height_h,real)
*set var Bf=MatProp(Width_Bf,real)
*set var tf=MatProp(Height_hf,real)
*set var tw=MatProp(Width_Bw,real)
*set var Ycm=operation((Bf*Bf*tf/2+tw*(height-tf)*Bf/2)/(Bf*tf+(height-tf)*tw))
*set var Zcm=operation((Bf*tf*(height-tf/2)+(tw*(height-tf))*(height-tf)/2)/(Bf*tf+(height-tf)*tw))
*set var Iz=operation((1.0/12*Bf*Bf*Bf*tf+(Bf*tf)*(Bf/2-Ycm)*(Bf/2-Ycm))+(1.0/12*tw*tw*tw*(height-tf)+(height-tf)*tw*(Bf/2-Ycm)*(Bf/2-Ycm)))
*set var temp=operation(height-tf)
*set var Iy=operation(pow(temp,3)*tw/12+pow(tf,3)*Bf/12+(tf*Bf)*(height-(tf/2)-Zcm)*(height-(tf/2)-Zcm)+(temp*tw)*((temp/2)-Zcm)*((temp/2)-Zcm))
*set var J=operation(Iy+Iz)
*set var A=operation(Bf*tf+(height-tf)*tw)
*elseif(strcmp(MatProp(Cross_section),"Circular")==0)
*set var D=MatProp(Diameter_D,real)
*set var A=operation(3.14159*D*D/4)
*set var Iz=operation(3.14159*D*D*D*D/64)
*set var Iy=operation(3.14159*D*D*D*D/64)
*set var J=operation(Iz+Iy)
*elseif(strcmp(MatProp(Cross_section),"General")==0)
*set var A=MatProp(Area_A,real)
*set var Iy=MatProp(Moment_of_inertia_about_local-y_Iyy,real)
*set var Iz=MatProp(Moment_of_inertia_about_local-z_Izz,real)
*set var J=MatProp(Torsional_moment_of_inertia_Iyz,real)
*endif
*set var E=MatProp(Elastic_modulus_E,real)
*set var G=MatProp(Shear_modulus_G,real)
*if(MatProp(Set_modification_factors,int)==1)
*set var Amod=MatProp(mod._A,real)
*set var Izmod=MatProp(mod._Izz,real)
*set var Iymod=MatProp(mod._Iyy,real)
*set var Jmod=MatProp(mod._Iyz,real)
*set var Avymod=MatProp(mod._Sy,real)
*set var Avzmod=MatProp(mod._Sz,real)
*set var A=operation(A*Amod)
*set var Iz=operation(Iz*Izmod)
*set var Iy=operation(Iy*Iymod)
*set var J=operation(J*Jmod)
*else
*set var Avymod=1.0
*set var Avzmod=1.0
*endif
*format "%6d%6g%6g%6g%6g%6g%6g%6g%6g"
section Elastic *ElasticSectionTag *E *A *Iz *Iy *G *J *Avymod *Avzmod
*else
*if(strcmp(MatProp(Cross_section),"Rectangular")==0)
*set var height=MatProp(Height_h,real)
*set var width=MatProp(Width_b,real)
*set var A=operation(width*height)
*set var Iz=operation(width*height*height*height/12)
*elseif(strcmp(MatProp(Cross_section),"Tee")==0)
*set var height=MatProp(Height_h,real)
*set var Bf=MatProp(Width_Bf,real)
*set var tf=MatProp(Height_hf,real)
*set var tw=MatProp(Width_Bw,real)
*set var Ycm=operation((Bf*tf*(height-tf/2)+(tw*(height-tf))*(height-tf)/2)/(Bf*tf+(height-tf)*tw))
*set var temp=operation(height-tf)
*set var Iz=operation(pow(temp,3)*tw/12+pow(tf,3)*Bf/12+(tf*Bf)*(height-(tf/2)-Ycm)*(height-(tf/2)-Ycm)+(temp*tw)*((temp/2)-Ycm)*((temp/2)-Ycm))
*set var A=operation(Bf*tf+(height-tf)*tw)
*elseif(strcmp(MatProp(Cross_section),"Circular")==0)
*set var D=MatProp(Diameter_D,real)
*set var A=operation(3.14*D*D/4)
*set var Iz=operation(3.14*D*D*D*D/64)
*elseif(strcmp(MatProp(Cross_section),"General")==0)
*set var A=MatProp(Area_A,real)
*set var Iz=MatProp(Moment_of_inertia_about_local-z_Izz,real)
*endif
*set var E=MatProp(Elastic_modulus_E,real)
*set var G=MatProp(Shear_modulus_G,real)
*if(MatProp(Set_modification_factors,int)==1)
*set var Amod=MatProp(mod._A,real)
*set var Izmod=MatProp(mod._Izz,real)
*set var Avymod=MatProp(mod._Sy,real)
*set var A=operation(A*Amod)
*set var Iz=operation(Iz*Izmod)
*else
*set var Avymod=1.0
*endif
*format "%6d%6g%6g%6g%6g%6g"
section Elastic *ElasticSectionTag *E *A *Iz *G *Avymod
*endif